### ISSUE TITLE
Setup Testing (Automated and Manual)

### ISSUE THREAD

**Issue by taslim-a-hussain** [solecms/soleink#10]
# Setup Testing (Automated and Manual)

## Description:
Let's level up our testing game for SoleInk by setting up both automated and manual testing! We'll be using Jest and React Testing Library.

## Tasks:
- [x] Setup Jest, react-testing-library for automated testing.
- [x] Write initial tests for key library components.
- [x] Ensure coverage reports are generated to keep track of our progress.
- [x] #12

Let me know if you'd like me to make any changes!
